trigger: none
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: BellevueCollege/bc-wordpress-devops-templates
      endpoint: github-service-connection

  pipelines:
    - pipeline: ci
      source: 'bc-funnelback-search-client'
      trigger:
        branches:
          include:
            - 'refs/tags/v*'

extends:
  template: templates/release/plugin-release.yml@templates
  parameters:

    pluginName: 'bc-funnelback-search-client'
    githubRepo: 'bc-funnelback-search-client'

    productionEnvironments:
      - name: KinstaProd
        displayName: 'Kinsta: Production'
        environment: kinsta-wwwbellevuecollegeedu
        sshServiceConnection: wwwbellevuecollegeedu
        variableGroup: kinsta-wwwbellevuecollegeedu
